### ISSUE TITLE
Sending messages bogs out with ! in the message

### ISSUE THREAD

**Issue by megatrond** [asbjornenge/keytalk#1]
The following does not work:

```
keytalk asbjornenge -m "whatever!"
```

It will leave you in the node CLI (i think)

Have not tried with ! somewhere else than the last position.

**Comment by asbjornenge** [comment]
@megatrond thats weird...!? Seems to work here... Check your messages!

Can you <code>keybase encrypt asbjornenge -m "whatever!"</code> ??

**Comment by megatrond** [comment]
It is a bash thing to repeat commands, come to think of it. Ignore ;p

-Trond Soras-
-Sent from mobile-
(please excuse typos)

**Comment by darthlukan** [comment]
Yeah, in both BASH and ZSH an escaping "\" is needed before "!", else the ending quote is escaped.  Just successfully tested in a message through keytalk to @asbjornenge
